### ISSUE TITLE
run time : error Cannot GET /

### ISSUE THREAD

**Issue by mitaldhas** [nemi-chand/ASPNETCore-SignalR-Angular-TypeScript#1]
i have done everythign step by step as suggested in tutorial and tried running the application. I get run time error : Cannot GET /

Also i downloaded the entire code and executed it and still i get same run time error.

Can you help ?

**Comment by nemi-chand** [comment]
@mitaldhas it seems something is missing. try to run in console mode or check output logs so that you'll get to know the actual error.
